configs:
- active: false
  name: A
  open_webui:
    api_key: <key A>
    location: http://127.0.0.1:3001/
- active: true
  name: B
  open_webui:
    api_key: <key B>
    location: http://127.0.0.1:3001
